# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9cc2fb35f69da9efee7e34aa5fd42060f7a723c9e7e85f75916c1f0729ead55ab1bd8babf496c152114310352529602abf53ade97e4d5c7007d1092c43d7e75

test:
  secret_key_base: b89b92a9901866226f4007c26aa0387e135f4a69d9d8bd4f5e33e48b708ad9c2e6aa23392b93ccbbecf339f4351e91fb31b7a4e881e16f2f0c0160b4472fa8a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
